# -*- coding: utf-8 -*-
"""Emotion Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cg3yx_4NVmX8bdjchswqU1CMxaGeHtRk
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np
import os

from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report, confusion_matrix

CASCADE_PATH = r"haarcascade_frontalface_default.xml"

from google.colab import files
uploaded = files.upload()

!unzip /content/Dataset.zip

!ls -F

TRAIN_DIR = r"/content/train"
TEST_DIR = r"/content/test"

EMOTIONS = "angry", "disgust", "fear", "happy", "neutral", "sad", "surprise"
IMG_SIZE = (64, 64)

label_to_id = {emo: i for i, emo in enumerate(EMOTIONS)}
id_to_label = {i: emo for emo, i in label_to_id.items()}

def load_emotion_data(root_dir):
    xs, ys = [], []
    for emo in EMOTIONS:
        emo_dir = os.path.join(root_dir, emo)
        if not os.path.isdir(emo_dir):
            print("Missing folder:", emo_dir)
            continue

        for fname in os.listdir(emo_dir):
            img_path = os.path.join(emo_dir, fname)
            img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            if img is None:
                continue

            img = cv2.resize(img, IMG_SIZE)
            xs.append(img.flatten().astype(np.float32) / 255.0)
            ys.append(label_to_id[emo])


    return np.array(xs), np.array(ys)

X_train, y_train = load_emotion_data(TRAIN_DIR)
X_test, y_test = load_emotion_data(TEST_DIR)
print("Train:", X_train.shape, "Test:", X_test.shape)

k_values = range(1, 16)
accuracies = []
best_k = None
best_acc = -1.0
best_knn = None

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    acc = knn.score(X_test, y_test)
    accuracies.append(acc)

    print(f"K = {k}, accuracy = {acc:.3f}")
    if acc > best_acc:
        best_acc, best_k, best_knn = acc, k, knn

print("\nBest K:", best_k, "accuracy:", best_acc)

plt.plot(list(k_values), accuracies)
plt.xlabel("K (neighbors)")
plt.ylabel("Accuracy")
plt.title("Accuracy vs K")
plt.grid(True)
plt.show()

pca = PCA(n_components=2)
X_train_2d = pca.fit_transform(X_train)
X_test_2d  = pca.transform(X_test)

test_acc =best_knn.score(X_test, y_test)

plt.figure(figsize=(6, 5))

colors = ["red", "orange", "green", "blue", "purple", "brown", "pink"]

for i, emo in enumerate(EMOTIONS):
    idx = (y_test == i)
    plt.scatter(
        X_test_2d[idx, 0],
        X_test_2d[idx, 1],
        s=10,
        color=colors[i],
        label=emo
    )

plt.title(f"PCA, KNN (k={best_k})\nTest accuracy = {test_acc:.2f}")
plt.xlabel("PCA component 1")
plt.ylabel("PCA component 2")
plt.legend(markerscale=2, fontsize=8)
plt.grid(True)
plt.show()

y_pred = best_knn.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix (predicted):")
print(cm)

print("\nClassification report:")
print(classification_report(y_test, y_pred, target_names=EMOTIONS))

plt.figure(figsize=(6, 5))
plt.imshow(cm, interpolation="nearest")
plt.title("Confusion matrix")
plt.xlabel("Predicted label")
plt.ylabel("True label")
plt.colorbar()

# use emotion names on axes
tick_marks = np.arange(len(EMOTIONS))
plt.xticks(tick_marks, EMOTIONS, rotation=45, ha="right")
plt.yticks(tick_marks, EMOTIONS)

plt.tight_layout()
plt.show()

face_cascade = cv2.CascadeClassifier(CASCADE_PATH)
cap = cv2.VideoCapture(0)   # or a video file path

if not cap.isOpened():
    print("Error: could not open video capture.")
else:
    while True:
        ret, frame = cap.read()
        if not ret:
            print("Error: failed to read frame.")
            break

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = face_cascade.detectMultiScale(gray, 1.3, 5)

        for (x, y, w, h) in faces:
            face = gray[y:y+h, x:x+w]
            face = cv2.resize(face, IMG_SIZE)
            vec = face.astype(np.float32).flatten() / 255.0
            vec = vec.reshape(1, -1)

            pred_id = best_knn.predict(vec)[0]
            emo = id_to_label[pred_id]

            cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
            cv2.putText(frame, emo, (x, y-10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)

        cv2.imshow("Emotion detection", frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()